### ISSUE TITLE
Racetype name in events

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#1]
In this case should be 'World Cup Prague' and 'World Cup Leipzig' ![image](https://user-images.githubusercontent.com/24532683/118594191-49c5fc00-b7a9-11eb-8190-8c0d63d1281c.jpeg)

**Comment by symlinktech** [comment]
Please check. Let us know if there are any mistakes.

**Comment by guille10k** [comment]
Ok with the main title, but country is repeated. It should be only the flag and GER

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Tab events not loading

**Comment by guille10k** [comment]
Ok, that is what I wanted. But maybe one more change? Take out the city from the Race Name and put it between the flag and the country, like this:
<img width="351" alt="Captura de pantalla 2021-07-24 a las 9 26 05" src="https://user-images.githubusercontent.com/24532683/126852116-0c666c4d-1613-4b61-8515-011875981d4f.png">

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok, perfect.
