### ISSUE TITLE
Events Order by date, not id

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#10]
![image](https://user-images.githubusercontent.com/24532683/124130872-86129a80-da7f-11eb-8dbf-485e37e1a3e8.png)

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Not loading events

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok

**Comment by guille10k** [comment]
Events not loading on the new APK

**Comment by guille10k** [comment]
On 'Past events' it should be order by date DESC, unlike 'Upcoming events'

Now it should be:
World Championships - Tacen SLO
World Cup - Markkleeberg GER
World Cup - Prague CZE
...

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Perfect. Only thing: events inside a race ordered by: event.age ASC, event.phase ASC

**Comment by symlinktech** [comment]
Please check

**Comment by guille10k** [comment]
Not correct. They are ordered now event.phase ASC, event.age ASC.

It should be **event.age ASC, event.phase ASC**

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok
