### ISSUE TITLE
Redesign Race Events

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#11]
No need for the title 'K1M', it's already on top. We take it out and move the Phase name on its place. 

Also, on 'Past events' we only show events which have runs associated. 

![image](https://user-images.githubusercontent.com/24532683/124131507-29fc4600-da80-11eb-8a4a-ed35643759da.jpeg)

**Comment by guille10k** [comment]
Also if an event has age != 3, we'll write the Age.name besides the Phase.name. Example: if age=1 and phase=1, "Heats1 - Junior". if age=3 and phase=1, "Heats1".

**Comment by guille10k** [comment]
Finally, when a race it's in "Upcoming events", we'll add a label on the left (where there was Heats1 before). Green label with "Finished" for events with COUNT(Run.id) > 0 and orange label with "Waiting" for events with COUNT(Run.id)=0
![IMG_140697270679-1](https://user-images.githubusercontent.com/24532683/124838477-e8105a00-dfc1-11eb-82b1-127e90808ffd.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok

**Comment by guille10k** [comment]
Events not loading on the new APK

**Comment by guille10k** [comment]
Perfect! Closing
