### ISSUE TITLE
Latest results on 'Home'

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#12]
I forgot to say that there is races with more than one age category.

So there should be one page on the 'Latest results' for every Category-Age event on the results (in the case of Tacen World championships, 8 pages right now)

![IMG_2958](https://user-images.githubusercontent.com/24532683/125178648-df1dc380-e221-11eb-9c56-962687b89053.PNG)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Good, but we need a title for every event. 

This title follows the next logic:
If (Event.Age=3) then title=Category.name
else title=Category.name+" "+Age.name

![IMG_AB4562C5398C-1](https://user-images.githubusercontent.com/24532683/126429429-db7df698-3c3f-478d-9642-eb0311f3cf53.jpeg)

**Comment by guille10k** [comment]
Perfect. Maybe letters in blue

**Comment by guille10k** [comment]
Also, it's displaying 'Senior'. It should display the Age.name only in cases of Event.age different of 3

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok

**Comment by guille10k** [comment]
I reopen this because it doesn't show all the finals. It has to show the first three from the events with phase IN (4,13).

Sorry, this is new changes in the sport.

**Comment by guille10k** [comment]
I would like to change which is the latest result showed. Can you tell me how the WHERE part of the query is? I imagined I said somethink like Race.raceType IN (1,4,8,13). In that case, we'll change it to RaceType.level <= 3

**Comment by symlinktech** [comment]
**Race Details**
select ra2.date, rt2.name, p2.name as place_name, p2.country,ra2.id as race_id,e2.id as event_id,e2.phase as phase_id FROM kdataspo_cbca.Run r2 LEFT JOIN kdataspo_cbca.Event e2 ON r2.event=e2.id LEFT JOIN kdataspo_cbca.Race ra2 ON e2.race=ra2.id LEFT JOIN kdataspo_cbca.RaceType rt2 ON ra2.raceType=rt2.id LEFT JOIN kdataspo_cbca.Place p2 ON ra2.place=p2.id WHERE rt2.level <= 3 AND e2.phase IN (4,13) AND e2.category=4 GROUP BY ra2.id ORDER BY ra2.date DESC LIMIT 1

Category Result

select r.position, a.name, a.surname, a.country,p.link,country.code,

CASE WHEN (cat.modality LIKE 'CSLX' AND e.phase!=8) THEN (CASE WHEN (cslx.qualified !='' AND cslx.total !='') THEN CONCAT(cslx.qualified,' ',cslx.total) ELSE NULL END) 
ELSE ROUND((r.time+r.penalties),2) END as time,e.date,e.age,b.id as athlete_id,
rt.name as race_name, cslx.number AS cslxrace

FROM kdataspo_cbca.Run r
LEFT JOIN kdataspo_cbca.Event e ON r.event=e.id
LEFT JOIN kdataspo_cbca.Boat b ON r.boat=b.id
LEFT JOIN kdataspo_cbca.Athlete a ON b.person=a.id
LEFT JOIN kdataspo_cbca.Photo p ON p.athId=b.id
LEFT JOIN kdataspo_cbca.Country country ON country.noc=a.country
LEFT JOIN kdataspo_cbca.CSLXrace cslx ON cslx.event=e.id AND cslx.boat=b.id
LEFT JOIN kdataspo_cbca.Race ON e.race=Race.id
LEFT JOIN kdataspo_cbca.RaceType rt ON Race.raceType=rt.id
LEFT JOIN kdataspo_cbca.Category cat ON e.category=cat.id

WHERE e.race=558
AND e.phase='".$race_details->phase_id."' AND e.category=4AND e.age=3

ORDER BY cslxrace ASC, r.position ASC LIMIT 3

**Comment by guille10k** [comment]
Ok, seems good now.

This should apply to Event notifications. Only races where RaceType.level <= 3

**Comment by symlinktech** [comment]
Done

**Comment by guille10k** [comment]
Perfect, thanks. 

Is there any way to have a notification test only for administrators?

**Comment by guille10k** [comment]
We are announcing every phase on LATEST RESULTS

So, for LATEST RESULTS, no more Event.phase IN (4,13). Every phase will be published on Home/Latest results

**Comment by symlinktech** [comment]
Please check

**Comment by guille10k** [comment]
Perfect

**Comment by guille10k** [comment]
Only one thing, we should specify the phase now. On the picture, “TRIALS” is {Phase.name} 
![7651DFA8-20BB-4284-80B7-01045952420B](https://user-images.githubusercontent.com/24532683/167780303-2ee0d079-50e9-4b45-b0b3-6f67bf4080f8.jpeg)

**Comment by symlinktech** [comment]
Please see skype video
