### ISSUE TITLE
Order of races in 'Upcoming events'

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#13]
It should be Race.date ASC. The earliest, the first. Opposite of the 'Past events'

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Upcoming events is ok. Past events has to be the opposite.

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Not loading data now 

https://user-images.githubusercontent.com/24532683/125934984-aa8d17e3-8a5a-4d4c-ae7e-9a776a4193c5.MP4

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Not loading with the new APK

**Comment by guille10k** [comment]
Perfect, closing issue.
