### ISSUE TITLE
Medals numbers

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#14]
On Athletes tab, on latest results, we'll make the same that on the bottom. When result is 1, 2 or 3, we show a medal

![IMG_F1B14FEF3972-1](https://user-images.githubusercontent.com/24532683/126430480-40c9bad9-20ec-432a-94d0-ed5ff5ab6bf3.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Perfect
