### ISSUE TITLE
Link to results

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#15]
These rows should be a link to the results of the race in the events tab

![IMG_A026CE83C83D-1](https://user-images.githubusercontent.com/24532683/126430777-1e4c1ca2-2fd6-4fb8-a8db-893901ed0c3c.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Perfect

**Comment by guille10k** [comment]
Perfect
