### ISSUE TITLE
News - athlete tags

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#16]
It has to came from kdataspo_cbca.Athlete

![IMG_3456](https://user-images.githubusercontent.com/24532683/126852646-96dfc3d8-dff4-4735-a5ca-9c62a16a7e88.PNG)

And then, on tab Athletes, on News sections, there has to be a list of news with that athlete tagged.

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
I think it's better this pop-up to be a search field, showing the three-four first results in format "Name SURNAME"

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok, but group by Athlete.id, not Boat.id.

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok, but they should be ordered by rank.

And in section Athletes, subsection News has disappeared?

**Comment by symlinktech** [comment]
Please test after we send you the APK
Comment : If there is no news for Athletes then News Tab does not show it

**Comment by guille10k** [comment]
Oook, understood.

Perfect both then
