### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#19]
We need to set notifications for:

Favorite athletes:
- Final position when a race is finished
- Race starting

Races:
- Race started
- Race finished

Manager:
- Inscriptions opened
- Last day of inscriptions
- Position of the teams

General:
- Custom messages

**Comment by symlinktech** [comment]
We added the setting in the profile page

**Comment by guille10k** [comment]
This? I don't see how that can work. Now notifications are working??

![IMG_32CAB4A21EF7-1](https://user-images.githubusercontent.com/24532683/134862658-15617952-bfc1-4705-8f6e-a7881cf0a0a3.jpeg)
)

**Comment by guille10k** [comment]
Perfect. Now we should work on notifications happening.

1st one: favorite athlete: final position when a race is finished
It should happen when there is a new row in kdataspo_cbca.Run where Run.boat is one of our favorites and the race has reached final results. 
It could follow the next query: 
SET @race=201;
SET @boat=223;

SELECT Run.position, Phase.name, Progression.boats

	FROM Run
		LEFT JOIN Event e ON Run.event=e.id
		LEFT JOIN Boat b ON Run.boat=b.id
		LEFT JOIN Athlete ath ON b.person=ath.id 
		LEFT JOIN Phase ON e.phase=Phase.id
		LEFT JOIN Race ON e.race=Race.id
		LEFT JOIN Progression ON (Race.progression=Progression.progressionMode AND e.phase=Progression.phase AND e.category=Progression.category AND Progression.raceType=Race.raceType AND YEAR(Race.date) BETWEEN Progression.season0 AND Progression.seasonF)
		
	WHERE e.race=@race AND e.category=b.boatKind AND b.id=@boat AND (Run.position>Progression.boats OR Phase.name LIKE '%final%')
	
	ORDER BY e.phase DESC

**Comment by guille10k** [comment]
Favorite athletes:
- Final position when a race is finished: "Your favorite athlete {athlete_name} finished {position}th on the {race_name}"
- Race starting: "Your favorite athlete {athlete_name} is about to race in {place_name}{race_name}"

Races:
- Race started: "{race_name} is getting started in {place_name}, {country}"
- Race finished: "Check results from {place_name}{race_name}"

Manager:
- Inscriptions opened: "Start making your teams for {place_name}{race_name}"
- Last day of inscriptions: "Make your teams! Last day for  {place_name}{race_name}" 
- Position of the teams: if team finished 10th position or better: "Congrats! Your team is {position} in {place_name}{race_name}". if team finished words than 10th position: "Your team {team_name} finished in {position}th" in {place_name}{race_name}"

**Comment by symlinktech** [comment]
We need to set notifications for:
Favourite athletes:
•	Final position when a race is finished
 	Status : Done
•	Race starting
Comment : Done
Races:
•	Race started
Comment : Done
•	Race finished
Status : Done

Manager:
•	Inscriptions opened
Status : Done
•	Last day of inscriptions
Status : Done
•	Position of the teams
Status : Done
General:
•	Custom messages
Status : Done
Link : https://www.slalommanager.com/admin/announcements

**Comment by guille10k** [comment]
Race starting for a favorite athlete:
```
SELECT MIN(e.date)

	FROM kdataspo_cbca.Event e
		LEFT JOIN kdataspo_fantasy.LeagueRound lr ON lr.race=e.race
		LEFT JOIN kdataspo_fantasy.BoatPrice bp ON (lr.roundOrder=bp.round AND lr.league=bp.league_id)
		LEFT JOIN kdataspo_cbca.Boat boat ON bp.boat=boat.id
		LEFT JOIN kdataspo_cbca.Athlete ath ON boat.person=ath.id
		
		
	WHERE e.race={race_id} AND ath.id={athlete_id}
	
	GROUP BY ath.id
```

Remember that favorite must be the athlete, not the boat

Race starting:

```
SELECT MIN(e.date)

	FROM kdataspo_cbca.Event e
		
	WHERE e.race={race_id}
	
	GROUP BY e.race
```

for the time of the notification, I'd like on the administrator a place where to set exact time of the notification for these two notifications. By default, the day before the date of the query, at 7.00pm CET.

**Comment by guille10k** [comment]
Position for favorite athletes will be notified after an event is completed. 

Now default is that Event.completed=0 and Event.is_notified=0.
When Event.completed => 1, we notify all the users with notifications ON, the position of their favorite athletes. Then, Event.is_notified=1.

We need to change the item on the notification page "Final position when a race is finished" for "Race position after an event is finished".

**Comment by guille10k** [comment]
For favorite athletes we need to add one more item:
- News publish about my favorite athletes

**Comment by symlinktech** [comment]
Done

**Comment by guille10k** [comment]
Ok. the screen where the user configure his preferences has to change:

Favourite Athletes:
- Position after an event is finished
- Race starting
- News published

All the rest is ok

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
First notification ("favourite athletes - position after an event is finished") and fifth ("Races - race finished") which should trigger at the same time when I set completed=1 on the event final of the race 199, where I have one of my favourite athletes, doesn't work

https://user-images.githubusercontent.com/24532683/148926659-b26b1102-2ebb-4d3a-a578-ed7140912f80.mov

**Comment by guille10k** [comment]
Title of the notification should be: "World championships results"
Message: "Your favourite athlete Elena APEL finished 2nd"
if more athletes involved, Message: "Your favourite athletes finished: Elena APEL, 2nd; Jessica FOX, 10th..."

<img width="311" alt="Captura de pantalla 2022-01-28 a las 12 24 33" src="https://user-images.githubusercontent.com/24532683/151538858-353f9ab6-03d4-4e90-9a13-c23b45b38006.png">

**Comment by guille10k** [comment]
Notifications working now
