### ISSUE TITLE
Header and options icon hiding on phone icons

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#20]
When I scroll down, the title and the options icon hide. I'd like then to stay a little under, not behind. Also, eliminate 'Welcome' title on the first page.

https://user-images.githubusercontent.com/24532683/127718470-1a5bd963-6ced-4576-9000-d757f2eef677.MP4

**Comment by symlinktech** [comment]
Checked and issue resolved
Test in the new app

**Comment by guille10k** [comment]
Still happening. You just deleted the title 'Welcome'.

https://user-images.githubusercontent.com/24532683/134862369-bc1ad173-1c2f-4a13-9d06-056f02a2b002.MOV

**Comment by guille10k** [comment]
Good job
