### ISSUE TITLE
Event results page title

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#21]
<img width="348" alt="Captura de pantalla 2021-08-13 a las 10 40 59" src="https://user-images.githubusercontent.com/24532683/129329919-be579992-6f60-45fe-aa99-ef747bc6060b.png">

**Comment by globalcreativity** [comment]
Done in local version. we will push it live on next version

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Top title, ok. 
Bottom title should be Category
Phase.name+'Results'

Example Final Results

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Perfect
