### ISSUE TITLE
Manager - add team

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#25]
Athletes are add in all the categories at the same time. I should be able to add it only on K1 or C1, for example
![IMG_0DBA57886B58-1](https://user-images.githubusercontent.com/24532683/130913241-7dd9deaf-9953-4acc-9df7-538647b7c226.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok
