### ISSUE TITLE
Manager section - show teams

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#26]
Once I click on one of the times, it should show the list of boats of that team.

![IMG_875C865D4DFC-1](https://user-images.githubusercontent.com/24532683/130913376-ae87df00-1f8b-4c85-bf9c-7dea7a1cb87d.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Good, but it could show the points of the athlete in that league.

![image](https://user-images.githubusercontent.com/24532683/136006514-730d1ce4-b320-4284-8315-8c01ce3b9054.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Perfect
