### ISSUE TITLE
Manager section - add team

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#27]
When the user is in this tab, can the + news button change to + team? Then a pop-up should be up, to chose which league to enter.

![IMG_875C865D4DFC-1](https://user-images.githubusercontent.com/24532683/130913376-ae87df00-1f8b-4c85-bf9c-7dea7a1cb87d.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Perfect
