### ISSUE TITLE
Manager section - races dropdown

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#28]
The races dropdown at the top of the screen should show the mother leagues from the fantasy db, not the races. In order date DESC

![IMG_875C865D4DFC-1](https://user-images.githubusercontent.com/24532683/130913376-ae87df00-1f8b-4c85-bf9c-7dea7a1cb87d.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok
