### ISSUE TITLE
Athletes section

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#29]
Change 'Follow her on:' for 'Follow them on:'

In news, there should show the news where the athlete is tagged.

![IMG_28F86FAE4984-1](https://user-images.githubusercontent.com/24532683/130913974-896a5975-ef53-4f9b-9aa8-b0c5488b2f43.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok
