### ISSUE TITLE
Name and athlete data not correct

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#3]
After clicking on An athlete on Events/result, the athlete data profile is not correct. The picture and result is, but not the athlete data (name, country,age)

Also last result is displaying three times 

![image](https://user-images.githubusercontent.com/24532683/118800965-c7b8fe80-b8a0-11eb-932c-e02a19ba43f3.jpeg)

**Comment by symlinktech** [comment]
Done
Let us know if there is any mistakes.

**Comment by guille10k** [comment]
Not correct. When I click on any athlete on the athlete list, a complete different athlete profile is opened

**Comment by guille10k** [comment]
Working fine now
