### ISSUE TITLE
Category button athlete not properly showing

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#36]
If I click on Jessica Fox, it shows 'C1M', but she is C1W and K1W, so something in this transition is broken. It happens in many athletes. This causes to not loading information.

Other thing is that this tag should be a button. So if I click on C1W it only shows information about Jessica Fox - C1W. If I click K1W, it only shows information about Jessica Fox - K1W. 

That means that category buttons in Tab 'stats' is no need. Only under the age.
![IMG_F8AD6440D9DE-1](https://user-images.githubusercontent.com/24532683/136746099-a20dfb88-e258-43e0-b85a-c3b77f0e2228.jpeg)

**Comment by symlinktech** [comment]
If I click on Jessica Fox, it shows 'C1M', but she is C1W and K1W, so something in this transition is broken. It happens in many athletes. This causes to not loading information.
Done

**Comment by guille10k** [comment]
Ok, but buttons C1W or K1W not working as buttons, only labels.

If I'm seeing the C1W profile, I should be able to click on K1W and change to the K1W profile.

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Now it works as a button, but the yellow color stays always on the same button.

https://user-images.githubusercontent.com/24532683/146531134-54e85d92-a275-4c55-8db9-edb75dfb74d4.mov

**Comment by symlinktech** [comment]
Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
Not working probably.

When I hit 'WK1', WK1 should be yellow and WC1 and WX1 blue
When I hit 'WC1', WC1 should be yellow and WK1 and WX1 blue
...

https://user-images.githubusercontent.com/24532683/147364727-a50c4171-e77f-4d93-83e5-28fb397a7b93.mov

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Ok!!
