### ISSUE TITLE
Rank number

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#38]
Rank number in both Athlete profile (picture num 1) and Athlete's list (picture number 2) have to come from a new table. This is the query:
"SELECT rpos.position AS date
								FROM Rank_pos rpos
								WHERE rpos.boat={Boat.id} AND rpos.release_date=(SELECT max(release_date) AS max_date FROM Rank_pos WHERE Rank_pos.boat={Boat.id})"

It simpliflies this number.

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok, good.
