### ISSUE TITLE
Manager filter: categories and countries

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#39]
I think only categories with boats available should be showed. I mean that if for a league there is no MC2 available, there is no need to show it. Same for countries.

For categories it can be done with the query: "SELECT cat.name 
FROM kdataspo_fantasy.BoatPrice bp 
	LEFT JOIN kdataspo_cbca.Boat b ON bp.boat=b.id
	LEFT JOIN kdataspo_cbca.Category cat ON b.boatKind=cat.id
WHERE bp.league_id=[league_id] AND bp.round=[round_id]
GROUP BY cat.id"

For countries it can be done with the query: "SELECT ath.country 
FROM kdataspo_fantasy.BoatPrice bp 
	LEFT JOIN kdataspo_cbca.Boat b ON bp.boat=b.id
        LEFT JOIN kdataspo_cbca.Athlete ath ON b.person=ath.id
	LEFT JOIN kdataspo_cbca.Category cat ON b.boatKind=cat.id
WHERE bp.league_id=[league_id] AND bp.round=[round_id]
GROUP BY ath.country"

<img width="382" alt="Captura de pantalla 2021-12-17 a las 11 39 10" src="https://user-images.githubusercontent.com/24532683/146531995-feecd259-3156-4071-b9b6-dc8cb5b84f6e.png">

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Looks good
