### ISSUE TITLE
Eliminate buttons

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#4]
There is no need for the label class. Also, we can make those labels C1W, K1W buttons and bigger, so we can eliminate those at the bottom 

![image](https://user-images.githubusercontent.com/24532683/118801538-6b0a1380-b8a1-11eb-8ae6-9717d6fea46f.jpeg)

**Comment by symlinktech** [comment]
Done

**Comment by guille10k** [comment]
Not fixed, still the same thing

**Comment by guille10k** [comment]
Ok for the eliminated buttons. 

This should be bigger, and there's should be one for each class of the athlete. The one that is being showing results should be in yellow. 

![image](https://user-images.githubusercontent.com/24532683/120917910-011ba780-c6b2-11eb-979f-920535c63048.jpeg)

**Comment by guille10k** [comment]
In some athletes it's showing wrong categories. For example, on the picture is showing C1M for Jessica FOX who is C1W or K1W or CSLXW.
![IMG_34CB4728D359-1](https://user-images.githubusercontent.com/24532683/136051533-ae237842-5ed4-451e-967f-c802a478174d.jpeg)
t

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Ok
