### ISSUE TITLE
Manager: new team

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#40]
Change the button from "Team add" to "New team"

<img width="394" alt="Captura de pantalla 2021-12-17 a las 11 49 39" src="https://user-images.githubusercontent.com/24532683/146533498-f545eda0-1664-43ed-b6cc-e78511853182.png">

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Good
