### ISSUE TITLE
Manager/Game: title

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#41]
Change this title to "Game: My teams"
<img width="369" alt="Captura de pantalla 2021-12-17 a las 11 51 14" src="https://user-images.githubusercontent.com/24532683/146533695-09f248ef-fb9b-4887-ac0d-57c8905106d2.png">

**Comment by guille10k** [comment]
Also on Results, change the Main title from "Events" to "Results"
<img width="413" alt="Captura de pantalla 2021-12-17 a las 11 54 16" src="https://user-images.githubusercontent.com/24532683/146534119-c6ca2328-e648-4489-8577-e574c66b4966.png">

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version
