### ISSUE TITLE
News: show athletes tagged on the news

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#42]
A tag to the athletes tagged

<img width="329" alt="Captura de pantalla 2021-12-17 a las 12 01 35" src="https://user-images.githubusercontent.com/24532683/146535224-c5aa4dd5-fbfd-480a-b153-18c41c97cb7b.png">

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Ok, but the athlete showed it's not the athlete that I tagged (I tagged Jiri Prskavec)

<img width="317" alt="Captura de pantalla 2021-12-24 a las 17 47 34" src="https://user-images.githubusercontent.com/24532683/147365398-e0825442-6d51-43c8-962c-4e1777edb443.png">

**Comment by symlinktech** [comment]
Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
Ok
