### ISSUE TITLE
Athletes: search by name

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#43]
It should search across all categories and sexes, without selecting a category or a sex

https://user-images.githubusercontent.com/24532683/146535578-4e20987e-8781-4c68-b0a3-91f64f436bab.mov

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Not seems to be working on men, only on women

**Comment by symlinktech** [comment]
Shared a video on your skype, you can check it is working fine with new apk.

**Comment by guille10k** [comment]
Ok, perfect
