### ISSUE TITLE
Athletes MK1 not showing

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#44]
No athletes showing on MK1. Also only one on MC1

**Comment by symlinktech** [comment]
Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
Ok now. 

But we need to make some changes here.
<img width="325" alt="Captura de pantalla 2021-12-23 a las 17 42 14" src="https://user-images.githubusercontent.com/24532683/147269243-39f86b5f-555d-4cb8-9c13-2eef9e0904ec.png">

If Women is selected, no need to show men categories under it. Same with Men. If Men is selected, no women categories.
If Women is selected, categories that should show: WK1, WC1, WX1, XC2.
If Men is selected, categories that should show: MK1, MC1, MX1, MC2, XC2.

If a search by name is made, is searches across all categories.

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
It's ok, we just need to change the order.
For women: WK1, WC1, WX1, XC2
For men: MK1, MC1, MX1, XC2, MC2

**Comment by symlinktech** [comment]
Please add ordering field to category table. Otherwise the data will not come according to your order.
Then we'll do it

**Comment by guille10k** [comment]
Done.

We can apply it to the latest results on home tab, and to the events on results tab also.

thanks

**Comment by symlinktech** [comment]
Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
<img width="287" alt="Captura de pantalla 2021-12-28 a las 8 31 37" src="https://user-images.githubusercontent.com/24532683/147540411-1fcf46f0-1422-410e-ab5c-9ce9bd4c3514.png">

Not applied here

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/147555287-2626e84e-a325-4ba1-992e-0bc45c1abaab.png)

Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
Perfect, thanks.

Results in WX1 and MX1 are not showing. I will open a new thread for this.
