### ISSUE TITLE
Athletes - statistics - new chart

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#45]
On top of the others, like this one:

Query: 
"SELECT position AS position, YEAR(release_date) AS season

FROM Rank_pos rpos

WHERE rpos.boat={boat_id} AND rpos.release_date=
  (SELECT MAX(release_date) FROM Rank_pos rpos2 WHERE rpos2.boat=rpos.boat AND YEAR(rpos.release_date)=YEAR(rpos2.release_date) 

GROUP BY YEAR(release_date))
ORDER BY rpos.release_date ASC"

<img width="442" alt="Captura de pantalla 2021-12-20 a las 20 23 26" src="https://user-images.githubusercontent.com/24532683/146821355-dc2aec11-2e81-4a17-b04a-f8cdf6b26ba9.png">

**Comment by symlinktech** [comment]
![jessica-fox](https://user-images.githubusercontent.com/47890547/147539232-a7f21e4e-980e-4874-8650-04ca2ab8b7af.png)
Here you can see category is mltiple i.e wc1, wk1. So we used barchart. If you click on the 1 category then graph will load 1 chart but by default it will load all caegory chart.

**Comment by guille10k** [comment]
Ok, works for me

**Comment by guille10k** [comment]
What about the Ranking chart?

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Ok, but it has to be different between categories

**Comment by symlinktech** [comment]
We loaded default first category statistics, if user click on other category then new category statistics  will fetch.

**Comment by guille10k** [comment]
Yes, I understand, and it's good for the rest of the charts. But for the ranking chart, it doesn't work. The only way would be doing one line chart for each category. Can we do that?

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/151321947-70fadb9f-75e8-4297-a393-56ae7edb5be1.png)
Please check boat_id = 207 above query

**Comment by guille10k** [comment]
It is normal. Jessica Fox in WC1 (boat 207) has been rank num 1 since 2014
