### ISSUE TITLE
Athletes - statistics - first table

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#46]
Can you remind the query for this table? I might need to modificate it.

Thanks

**Comment by symlinktech** [comment]
chart_data Query: 
select p.name,COUNT(r.id) as count,case when e.phase>1 then CONCAT(COUNT(r.id)/(SELECT COUNT(r.id) FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (340,3881) AND rt.level<=2 AND e.phase=1)*100,'%') end as 'perc' FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id LEFT JOIN Phase p ON e.phase=p.id WHERE r.boat IN (340,3881) AND rt.level<=2 GROUP BY e.phase union SELECT 'Medals' AS name,COUNT(r.id),CONCAT(COUNT(r.id)/(SELECT COUNT(r.id) FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (".$athlete_id.") AND rt.level<=2 AND e.phase=1)*100,'%') FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id LEFT JOIN Phase p ON e.phase=p.id WHERE r.boat IN (340,3881) AND rt.level<=2 AND e.phase=4 AND r.position <= 3

chart_percentage Query:

select 'clean_runs',COUNT(r.id) as count FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (340,3881) AND rt.level<2 AND r.penalties=0 union SELECT '+2 runs',COUNT(r.id) FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (340,3881) AND rt.level<2 AND r.penalties=2 union SELECT '>+2 runs, no 50',COUNT(r.id) FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (340,3881) AND rt.level<2 AND r.penalties BETWEEN 3 AND 49 union SELECT '50 runs',COUNT(r.id) FROM Run r LEFT JOIN Event e ON r.event=e.id LEFT JOIN Race ra ON e.race=ra.id LEFT JOIN RaceType rt ON ra.raceType=rt.id WHERE r.boat IN (340,3881) AND rt.level<2 AND r.penalties>=50

**Comment by guille10k** [comment]
I meant the first table, the summary of P-M-F of every type of race

**Comment by symlinktech** [comment]
select tableStarts.name, tableStarts.played, tableFinals.finals, tableMedals.medals FROM (SELECT CASE WHEN e.age=3 THEN rk.name ELSE CONCAT(ag.name,' ',rk.name) END AS name,COUNT(r.id) AS played,rk.id AS rkId, e.age AS agId FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id LEFT JOIN Age ag ON e.age=ag.id WHERE r.boat IN (207,386,3838) AND e.phase=1 AND rk.id NOT IN (3,9) AND e.category IN (4,2,8) GROUP BY rk.id,e.age)tableStarts LEFT JOIN (SELECT COUNT(r.id) AS finals, rk.id AS rkId, e.age AS agId FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id WHERE r.boat IN (207,386,3838) AND e.phase=4 AND rk.id NOT IN (3,9) AND e.category IN (4,2,8) GROUP BY rk.id,e.age)tableFinals ON tableStarts.rkId=tableFinals.rkId AND tableStarts.agId=tableFinals.agId LEFT JOIN (SELECT COUNT(r.id) AS medals, rk.id AS rkId, e.age AS agId FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id WHERE r.boat IN (207,386,3838) AND e.phase=4 AND r.position <= 3 AND rk.id NOT IN (3,9) AND e.category IN (4,2,8) GROUP BY rk.id,e.age)tableMedals ON tableStarts.rkId=tableMedals.rkId AND tableStarts.agId=tableMedals.agId ORDER BY FIELD (tableStarts.rkId,8,2,4,3,1,13,10,11,15,14,22,18,19,5,21,16,17,6,7)

**Comment by guille10k** [comment]
Thanks. We need to change this table as follows, giving the same fields, but not so many rows:

`select CASE WHEN tableStarts.level=3 THEN "Ranking race" ELSE tableStarts.name END AS name, SUM(tableStarts.played) AS played, SUM(tableFinals.finals) AS finals, SUM(tableMedals.medals) AS medals FROM 

(SELECT CASE WHEN e.age=3 THEN rk.name ELSE CONCAT(ag.name,' ',rk.name) END AS name,COUNT(r.id) AS played,rk.id AS rkId, e.age AS agId, rk.level,rk.order,ag.orderImportance AS ageOrder FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id LEFT JOIN Age ag ON e.age=ag.id WHERE r.boat IN ({boat_id1},{boat_id2},{boat_id3}) AND e.phase=1 AND rk.level <=3  GROUP BY rk.id,e.age)tableStarts 

LEFT JOIN 

(SELECT COUNT(r.id) AS finals, rk.id AS rkId, e.age AS agId FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id WHERE r.boat IN ({boat_id1},{boat_id2},{boat_id3}) AND e.phase=4 AND rk.level <=3 GROUP BY rk.id,e.age)tableFinals 

ON tableStarts.rkId=tableFinals.rkId AND tableStarts.agId=tableFinals.agId 

LEFT JOIN 

(SELECT COUNT(r.id) AS medals, rk.id AS rkId, e.age AS agId FROM RaceType rk LEFT JOIN Race ra ON rk.id=ra.raceType LEFT JOIN Event e ON ra.id=e.race LEFT JOIN Run r ON r.event=e.id WHERE r.boat IN ({boat_id1},{boat_id2},{boat_id3}) AND e.phase=4 AND r.position <= 3 AND rk.level <=3 GROUP BY rk.id,e.age)tableMedals 

ON tableStarts.rkId=tableMedals.rkId AND tableStarts.agId=tableMedals.agId 


GROUP BY CASE 
	WHEN tableStarts.level=1 THEN tableStarts.name
	WHEN tableStarts.level=2 THEN tableStarts.name
	ELSE 'Ranking race'
	END

ORDER BY tableStarts.level, tableStarts.order, tableStarts.ageOrder
`

**Comment by symlinktech** [comment]
Status Check it.

**Comment by guille10k** [comment]
Good. 

Only one detail, the header doesn't match the result. We have to switch the F with the M. Just the header.
<img width="297" alt="Captura de pantalla 2022-01-27 a las 7 50 33" src="https://user-images.githubusercontent.com/24532683/151306928-9e3770cc-9950-47b7-970e-eb5c873a9ff2.png">

**Comment by guille10k** [comment]
Good.

We will change two small details. Change P for S (Starts instead of Played) and we'll switch columns M and F. Like the picture.

Thanks

<img width="297" alt="Captura de pantalla 2022-01-27 a las 7 53 44" src="https://user-images.githubusercontent.com/24532683/151308953-3226aca4-3406-4e20-9f34-9aef088ed0b9.png">

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version
