### ISSUE TITLE
Results: WX1 and MX1 results not showing

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#47]
Results from these categories not showing

**Comment by symlinktech** [comment]
Please check query

select r.position, a.name, a.surname, a.country,p.link,country.code, ROUND((r.time+r.penalties),2) as time,e.date,e.age,b.id as athlete_id,(select rt2.name as race_name FROM kdataspo_cbca.Run r2 LEFT JOIN kdataspo_cbca.Event e2 ON r2.event=e2.id LEFT JOIN kdataspo_cbca.Race ra2 ON e2.race=ra2.id LEFT JOIN kdataspo_cbca.RaceType rt2 ON ra2.raceType=rt2.id WHERE rt2.level <= 2 AND e2.phase IN (4,13) GROUP BY ra2.id ORDER BY ra2.date DESC LIMIT 1) as race_name FROM kdataspo_cbca.Run r LEFT JOIN kdataspo_cbca.Event e ON r.event=e.id LEFT JOIN kdataspo_cbca.Boat b ON r.boat=b.id LEFT JOIN kdataspo_cbca.Athlete a ON b.person=a.id LEFT JOIN kdataspo_cbca.Photo p ON p.athId=b.id LEFT JOIN kdataspo_cbca.Country country ON country.noc=a.country WHERE e.race= (select ra2.id FROM kdataspo_cbca.Run r2 LEFT JOIN kdataspo_cbca.Event e2 ON r2.event=e2.id LEFT JOIN kdataspo_cbca.Race ra2 ON e2.race=ra2.id LEFT JOIN kdataspo_cbca.RaceType rt2 ON ra2.raceType=rt2.id WHERE rt2.level <= 2 AND e2.phase IN (4,13) GROUP BY ra2.id ORDER BY ra2.date DESC LIMIT 1) AND r.position <=3 AND e.phase IN (4,13) AND e.category=8 AND e.age=3  ORDER BY r.position ASC

**Comment by guille10k** [comment]
Ok, I fixed the query. It must be:

`select r.position, a.name, a.surname, a.country,p.link,country.code, 

CASE WHEN (cat.modality LIKE 'CSLX' AND e.phase!=8) THEN CONCAT(cslx.qualified,' ',cslx.total)
		ELSE ROUND((r.time+r.penalties),2) END as time,e.date,e.age,b.id as athlete_id,
	rt.name as race_name, cslx.number AS cslxrace 

FROM kdataspo_cbca.Run r 
	LEFT JOIN kdataspo_cbca.Event e ON r.event=e.id 
	LEFT JOIN kdataspo_cbca.Boat b ON r.boat=b.id 
	LEFT JOIN kdataspo_cbca.Athlete a ON b.person=a.id 
	LEFT JOIN kdataspo_cbca.Photo p ON p.athId=b.id 
	LEFT JOIN kdataspo_cbca.Country country ON country.noc=a.country
	LEFT JOIN kdataspo_cbca.CSLXrace cslx ON cslx.event=e.id AND cslx.boat=b.id
	LEFT JOIN  kdataspo_cbca.Race ON e.race=Race.id
	LEFT JOIN  kdataspo_cbca.RaceType rt ON Race.raceType=rt.id
	LEFT JOIN  kdataspo_cbca.Category cat ON e.category=cat.id
	
WHERE e.race={race_id} 
AND e.phase={phase_id} AND e.category={category_id} AND e.age={age_id} 

ORDER BY cslxrace ASC, r.position ASC`

**Comment by guille10k** [comment]
And sorry, I just realized now. For WX1 and MX1 results have to be shown differently for phase.id IN (10,11,12). Like this for these cases:
 
<img width="359" alt="Captura de pantalla 2021-12-28 a las 15 37 42" src="https://user-images.githubusercontent.com/24532683/147577068-8e625d7b-5975-46b1-99c5-f5f6a8168c08.png">

**Comment by symlinktech** [comment]
Please Check. Let us know if there are any mistakes

**Comment by guille10k** [comment]
It looks good, but no need to show (+) if NULL

And we still need to group the rows by cslx.number

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Perfect
