### ISSUE TITLE
Latest results

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#48]
No need for time and penalties on Category.modality='CSLX'. Just the name. 

![image](https://user-images.githubusercontent.com/24532683/147858876-a9bf17f3-380f-456d-b4df-344d474d6208.jpeg)

**Comment by guille10k** [comment]
Also this results are not correct

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Perfect
