### ISSUE TITLE
Athletes - favourites

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#49]
Can we show a button for showing user favourites same way as the others? On clicking the star, it would show only the user favourites, if the user is logged in. if it is not, it will throw an alert with "Log in for favourite athletes".

![Captura de pantalla 2022-01-06 a las 6 27 56](https://user-images.githubusercontent.com/24532683/148333368-67ade2ae-faf9-4736-9009-41e182322765.png)

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Perfect
