### ISSUE TITLE
Athletes list

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#5]
Order by Rank ASC

When at the top and pulling down the list, a field for search has be shown

![image](https://user-images.githubusercontent.com/24532683/119265357-b47e9980-bbe6-11eb-96fd-55afc3d3266e.png)

**Comment by symlinktech** [comment]
Done but have some design issue
we will fix it

**Comment by guille10k** [comment]
Ok, I'll wait
