### ISSUE TITLE
Results - Live/Video links

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#50]
This buttons will show only if the link exists on the table Link.

<img width="327" alt="Captura de pantalla 2022-01-09 a las 20 30 22" src="https://user-images.githubusercontent.com/24532683/148698058-94ca23f8-710e-490d-906c-f31a7c071301.png">

Live link, only if 

`SELECT link, CONCAT(Phase.name,' ',Category.name,' ',Link_kind.name) AS link_name
FROM Link 
LEFT JOIN Link_kind ON Link.kind=Link_kind.id
LEFT JOIN Phase ON Link.phase=Phase.id
LEFT JOIN Category ON Link.category=Category.id
WHERE race=race_id AND kind=1
ORDER BY Link.phase ASC, Category.order ASC`

Video link, same query but with kind=2

In case of one result, redirect directly to the link. In case of more than one result, we could show a list of links (like the one for selecting athletes on the news), showing every row results, the link_name.

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Works good on video links. 
I doesn't show Live links. Euros Ivrea 2021 should show it and it doesn't

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/150768506-49ecfc3e-9ec6-4ab7-aa3d-ba2e48f8c88a.png)
There no phase id. Please check

**Comment by guille10k** [comment]
Oh phase=0, the link is valid for the whole race

**Comment by symlinktech** [comment]
Will there be a live link for the race?

**Comment by symlinktech** [comment]
Will there be a live link for the race?
If the live link is one then check if it is ok

**Comment by guille10k** [comment]
we show the same icons as now. If there is only one link for video for the race, we open the link straigthaway. If there is more than one link for video for the race, we show a pop-up with the different links, with the description. If there is no link for video for the race, we show no icon.
Same for live results link.

**Comment by guille10k** [comment]
we show the same icons as now. If there is only one link for video for the race, we open the link straigthaway. If there is more than one link for video for the race, we show a pop-up with the different links, with the description. If there is no link for video for the race, we show no icon.
Same for live results link.

**Comment by guille10k** [comment]
Perfect!
