### ISSUE TITLE
Favourite athletes - wrong athletes

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#51]
Those selected as favourites on the list of athletes, are not the same on the list of favourite athletes.

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Works good from Athlete profile. 
Wrong from athletes list.

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Ok
