### ISSUE TITLE
Notifications - Race finished for favourite athlete

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#54]
Title of the notification should be: "Bratislava final results" {Place.name} {Phase.name} results
Message: "Ricarda FUNK finished 2nd"

Observations: 
- wrong cardinal position: st, nd, th...
- clicking on notification should open the event on the app (i.e. on this notification, on clicking the app should show World Championships WK1 final

<img width="286" alt="Captura de pantalla 2022-02-01 a las 11 34 51" src="https://user-images.githubusercontent.com/24532683/151953304-421b7806-084a-4b77-b60b-54e9167f37a8.png">

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
good
