### ISSUE TITLE
Notifications - all news

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#56]
We should add one new kind of notification, "All news". That would notify every time a news is published, under the category of 'General'

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Works perfectly.

Only thing, the format.
Notification title: 'News: {news_title}'
Notification title: {news_short_text}

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Ok, we just change slighlty the text: "was tagged in this post" for just "in this post"

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Good. Can we make that clicking on this notification opens the post?

**Comment by guille10k** [comment]
Good job
