### ISSUE TITLE
News

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#57]
News should be inactive when published until an administrator (me), activates them. Is it possible to send an email to the administrator (me) when an user tries to publish a news? Then I will activate it. And the user should get a notification in that moment saying that the administrator have to review the news.

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Good job with the notification. We just need to change the format.

Title: "News: {news_title}"
Message: "{athlete_name} was tagged in this post"

When I click "Save" on editing news, it keeps on "Please wait..." for a while, and then back to editing news without a message of success or failure.

<img width="291" alt="Captura de pantalla 2022-02-04 a las 12 19 07" src="https://user-images.githubusercontent.com/24532683/152520416-2e3473bc-97f0-40f4-9d6d-254c84dd3d2b.png">

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Good now

**Comment by guille10k** [comment]
Good now.

If the same post contains more than one favourite athlete, there should be only one notification:
"Ricarda FUNK, Jiri PRSKAVEC were tagged in this post"

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Ok, only two things:
- when I receive a notification for a news where my favourites athletes are tagged, I don't receive the notification for 'all news', because then it is two notifications for the same post
![IMG_A93A4710225A-1](https://user-images.githubusercontent.com/24532683/152775476-d59a7515-6804-49fc-a20f-e8bddaeeb39c.jpeg)

**Comment by guille10k** [comment]
Now it is working ok when there is favourite athletes on the post.

If there is not favourite athletes on the post, it has to be:
Title : same as before
Text : short description of the post

**Comment by symlinktech** [comment]
Yes, Check it

**Comment by guille10k** [comment]
Not working as you can see. For this case, the text should be 'Trying', which is the short description of the post.

![IMG_91B050EBF5CC-1](https://user-images.githubusercontent.com/24532683/153020828-0cb881c7-dcbe-4231-ba2f-5bc1ea7773a2.jpeg)

**Comment by symlinktech** [comment]
Check it

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by guille10k** [comment]
Good
