### ISSUE TITLE
Little bugs: home page

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#59]
last two squares (Phase.modality='CSLX') are shorter than the others, because of the time.
![IMG_5166](https://user-images.githubusercontent.com/24532683/152680326-da423d60-9692-4ab1-945a-48a5462bc68c.PNG)
![IMG_5167](https://user-images.githubusercontent.com/24532683/152680327-21b18068-64f3-4d94-89d0-5bf6b6d52167.PNG)

**Comment by symlinktech** [comment]
Not clear

**Comment by guille10k** [comment]
<img width="914" alt="Captura de pantalla 2022-02-07 a las 12 04 34" src="https://user-images.githubusercontent.com/24532683/152776898-f372fe1c-3ef3-49cc-8d48-4138eb693464.png">

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/152790020-c6c6d3f6-f55f-499b-a165-758ebb5b5ba1.png)

**Comment by guille10k** [comment]
I know. But can't you fill it with an empty space? It doesn't look good if it is not the same.

**Comment by guille10k** [comment]
Still happening

**Comment by guille10k** [comment]
Still happening

**Comment by guille10k** [comment]
Good
