### ISSUE TITLE
News input

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#6]
We need to add two new fields for the news form: 'News source'. It will be the URL of what an user wants to add. Most of the news won't be a full article, but a reference. And also a name for that source.

So the fields should be: News title, News source url, News source name, Athlete tags, Short descritpion, Image, Full text (optional).

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok

**Comment by guille10k** [comment]
I don't see any of the new fields I pointed out.

**Comment by guille10k** [comment]
Good, closing, but more work to do on next issue.
