### ISSUE TITLE
Little bugs: Name of the races

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#61]
Can we change the name of the race to 

if (Race.difName)
   RaceType.name." ".Race.difName
else
   RaceType.name

**Comment by symlinktech** [comment]
We don't understand what's Race.difName. Please explain more

**Comment by guille10k** [comment]
It's a field on Race.table
<img width="276" alt="Captura de pantalla 2022-02-07 a las 11 13 39" src="https://user-images.githubusercontent.com/24532683/152768370-673e1470-e878-4193-aa5d-5a8ad84830e5.png">

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Not working
![IMG_050E192B6591-1](https://user-images.githubusercontent.com/24532683/152957453-4409dc45-d9d2-4cd6-b154-6a503753dd58.jpeg)
<img width="678" alt="Captura de pantalla 2022-02-08 a las 10 25 40" src="https://user-images.githubusercontent.com/24532683/152957478-2cde45d6-7c5b-4c66-93c2-3418096919f2.png">

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Perfect
