### ISSUE TITLE
Athletes: not all latests results are showing

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#62]
Only when a category is not selected. But it should show the results on all the categories

![IMG_FFAB9F4A06BC-1](https://user-images.githubusercontent.com/24532683/152680924-18cec68d-de2a-4eec-bce9-6f37e4ef56ed.jpeg)

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Nope. 

Now it's showing more results, but not the latest results. No results after Olympic Games from Jessica. And there should be at least 9. 

What is the SQL query?

**Comment by symlinktech** [comment]
select CASE WHEN ag.id = 3 THEN CONCAT(rt.name) ELSE CONCAT(ag.name," ",rt.name) END AS racetype_name, pl.name as place_name, pl.country, ph.name,DATE_FORMAT(Race.date, "%d") as day,DATE_FORMAT(Race.date, "%b %y") as month_year,c.code as country_code,cat.name as category_name, CASE WHEN Event.phase = 2 THEN r.position+pr.boats ELSE r.position END AS position,ph.name AS phase_name,Event.id AS event_id,Race.id FROM kdataspo_cbca.Race LEFT JOIN kdataspo_cbca.Event ON Race.id=Event.race AND Event.phase=(SELECT MAX(e2.phase) FROM kdataspo_cbca.Event e2 LEFT JOIN kdataspo_cbca.Run r2 ON e2.id=r2.event WHERE r2.boat IN (207,386,3838) AND e2.race=Event.race) LEFT JOIN kdataspo_cbca.Run r ON Event.id=r.event LEFT JOIN kdataspo_cbca.Boat b ON b.id=r.boat LEFT JOIN kdataspo_cbca.Athlete a on b.person=a.id LEFT JOIN kdataspo_cbca.RaceType rt ON Race.raceType=rt.id LEFT JOIN kdataspo_cbca.Place pl ON Race.place=pl.id LEFT JOIN kdataspo_cbca.Progression pr ON (Event.category=pr.category AND Event.phase=pr.phase AND rt.id=pr.raceType) LEFT JOIN kdataspo_cbca.Phase ph ON Event.phase=ph.id LEFT JOIN kdataspo_cbca.Country c ON c.noc = pl.country LEFT JOIN kdataspo_cbca.Category cat ON cat.id=Event.category LEFT JOIN kdataspo_cbca.Age ag ON Event.age=ag.id WHERE b.id IN (207,386,3838) AND cat.id= 4 AND rt.level<2 AND Event.phase != 13 GROUP BY Race.id ORDER BY Race.date DESC LIMIT 4

**Comment by symlinktech** [comment]
Please check it. We remove Event.phase != 13

**Comment by guille10k** [comment]
Final WHERE has to be `WHERE b.id IN (207,386,3838) AND rt.level<=3`

instead of 'WHERE b.id IN (207,386,3838) AND cat.id= 4 AND rt.level<2 AND Event.phase != 13'

**Comment by symlinktech** [comment]
Check it

**Comment by guille10k** [comment]
Ok, but there should be only five rows and order by event.date DESC

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Good
