### ISSUE TITLE
Athletes/stats: Chart Run behaviour

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#66]
When no category is selected, all the phases have to be included.

When a category is selected, then Category.modality=Phase.modality
![IMG_EE116C06B5C9-1](https://user-images.githubusercontent.com/24532683/154261584-26f0c3a5-88f0-4a04-8b95-9e6c220d567e.jpeg)

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by symlinktech** [comment]
Check latest version of google playstore it is published.

**Comment by guille10k** [comment]
It has erratic behaviour. The x-axis values change while scrolling up and down

**Comment by symlinktech** [comment]
Done
