### ISSUE TITLE
Athletes/stats: Chart penalties

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#67]
When Category.modality='CSL', the chart has to show the current data: clean_runs, +2 runs, >+2 runs, 50 runs. It is ok now when no category is selected, but it has to be like this for WK1, MK1, WC1, MC1 (modality='CSL')

When Category.modality='CSLX', the chart has to show the disticnt penalties it has found on the table CSLXRace joined with Run. Group By them, showing the COUNT, with the following query.

`SELECT CSLXrace.total,COUNT(Run.id)

FROM Run
LEFT JOIN Event ON Run.event=Event.id
RIGHT JOIN CSLXrace ON (Event.id=CSLXrace.event AND CSLXrace.boat=Run.boat)
LEFT JOIN Category ON Event.category=Category.id
LEFT JOIN Phase ON Event.phase=Phase.id

WHERE Phase.modality='CSLX' AND Run.boat IN (3835)

GROUP BY CSLXrace.total`
![IMG_0E1BB657194D-1](https://user-images.githubusercontent.com/24532683/154264373-a7640c2c-d5b4-498f-836a-727945f7f123.jpeg)

**Comment by symlinktech** [comment]
Done in local. We will push it to live on next version

**Comment by symlinktech** [comment]
Check latest version of google playstore it is published.
