### ISSUE TITLE
News: creating during night mode

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#69]
In iOS, when in night mode, it's difficult to read what you are writing when creating a new news.

**Comment by symlinktech** [comment]
Done

**Comment by symlinktech** [comment]
Done

**Comment by symlinktech** [comment]
Done

**Comment by guille10k** [comment]
Ok, thanks. Have you done it in every form, or just news creating? It happens also on 'Search' fields and forms in user profile.

**Comment by symlinktech** [comment]
Please share screenshots, we are not getting it
