### ISSUE TITLE
This list should be Mother Leagues

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#7]
On Athlete profile/Manager 

![image](https://user-images.githubusercontent.com/24532683/120916870-67053080-c6ac-11eb-9af6-50108d022af1.png)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Not working. This list is kdataspo_cbca.Race.

It should be kdataspo_fantasy.League (but only those with League.language_type = "mother"

**Comment by guille10k** [comment]
Perfect! Closing issue. 

I think you should do the same fix on the tab Manager
