### ISSUE TITLE
Athlete news tab

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#72]
Order of the news should be reversed. Newer news first. 

Also, height of the rows should always be the same, not depending on the picture.
![IMG_66774688D678-1](https://user-images.githubusercontent.com/24532683/157450859-4bc1c452-4114-4943-98ed-554df744e553.jpeg)

**Comment by symlinktech** [comment]
check it

**Comment by guille10k** [comment]
Order ok. Row height not yet 

And I’ve spot one more bug: when clicking on Jessica on latest results, profile doesn’t show the news

**Comment by symlinktech** [comment]
if we make the row height same, then image will be cropped. Should we make it like this?

![image](https://user-images.githubusercontent.com/47890547/157600890-89630038-985b-4e6c-919c-a898c06006f7.png)

**Comment by guille10k** [comment]
Yes, don't worry.

**Comment by symlinktech** [comment]
Locally Done
