### ISSUE TITLE
Night mode on manager/creating teams

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#78]
Continues to give problems: input text cells in black.
![PHOTO-2022-05-25-07-55-06](https://user-images.githubusercontent.com/24532683/170195494-5675491c-99e5-4ec3-a006-7f9dc0be06d5.jpg)

**Comment by symlinktech** [comment]
Didn't find any issue. Download the app from app store and check.
It is clear that you are testing old version as the blue color is not correct.

![Skype_Picture_2022_06_07T06_16_19_234Z](https://user-images.githubusercontent.com/47890547/172309855-79c7daa6-05ea-4e3c-9117-b45aed7675ba.jpeg)

**Comment by guille10k** [comment]
Seems ok too. I will tell the user that reported to me.

Thanks
