### ISSUE TITLE
Tab athletes links

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#8]
On tab Athletes, on clicking on an athlete row, it doesn't open the right athlete. Same thing that used to happen in Events, that you already fixed.

**Comment by guille10k** [comment]
Like the video. Every time I click on an athlete it opens the wrong profile 

https://user-images.githubusercontent.com/24532683/126174739-005bf067-2066-4764-bfd1-6a0daa7e0a42.MOV

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Still not working. I've observed that on Athletes tab, the link is using the Athlete.id. It should use the Boat.id.

**Comment by guille10k** [comment]
Perfect! Closing issue
