### ISSUE TITLE
Home/latest results not showing the proper phase

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#83]
It should show the final, not the heats 1.

Always the max Event.phase that it can find.
![IMG_D8D4A891EE9C-1](https://user-images.githubusercontent.com/24532683/172136158-01c99e26-628c-4133-b631-22221eff8f8a.jpeg)

**Comment by symlinktech** [comment]
Please check

**Comment by guille10k** [comment]
Ok, but now there is one category missing, MK1, why?

**Comment by symlinktech** [comment]
Please Check and let us know if there is any mistake.

**Comment by guille10k** [comment]
All categories good, but the MK1, it's still showing Heats 1

**Comment by symlinktech** [comment]
Please Check and let us know if there is any mistake.

**Comment by guille10k** [comment]
good now
