### ISSUE TITLE
New arrangement for homepage

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#86]
- Change the big logo + name to a little logo on top right
- Take out the +News button on home page
- Bring every section up (space of the previous logo)
- Change the name of the "Incoming league" section to "Manager game
![IMG_1C148F12F3BA-1](https://user-images.githubusercontent.com/24532683/173821484-2b98c7dc-6dd3-4c11-bdde-6a99b509ee30.jpeg)
"

**Comment by symlinktech** [comment]
Done Locally. We will push next version

**Comment by guille10k** [comment]
Perfect
