### ISSUE TITLE
Home: Add one slide to the carrousel

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#88]
This section will start with a picture:
<img width="358" alt="Captura de Pantalla 2022-06-15 a las 13 58 12" src="https://user-images.githubusercontent.com/24532683/173821788-bab305f6-5ca1-4fca-80be-fde016de731e.png">

Which I can change on the slalommanager admin. Maybe under a new section called App settings? Where I can send them a picture for this purpose and set the initial date of publication and the final date of publication.

I would look like this:
<img width="391" alt="Sin título 2" src="https://user-images.githubusercontent.com/24532683/173822518-9a063e06-6c99-43c8-b9ab-31b165abbbd5.png">

**Comment by guille10k** [comment]
Slight change: if the race has links associated, we'll show them as we do with the results.
<img width="391" alt="173822518-9a063e06-6c99-43c8-b9ab-31b165abbbd5" src="https://user-images.githubusercontent.com/24532683/174245448-307ce5aa-221a-444b-804d-9dfdb65cb233.png">

**Comment by symlinktech** [comment]
Done Locally. We will push next version

**Comment by guille10k** [comment]
It's good but live results and video links have to be for the race being. Maybe on the App Settings on the admin I can select a race, so we show here the results and video from that race?

**Comment by symlinktech** [comment]
Please check. If let us know if there are any mistakes

**Comment by guille10k** [comment]
Good job with the links and race.

Only thing, if current date not between initial date of publication or final date of publication, this slide of the carrousel should not show. First would be latest results.

**Comment by symlinktech** [comment]
Please check. If let us know if there are any mistakes

**Comment by guille10k** [comment]
Yes, works now.
