### ISSUE TITLE
Title missing

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#9]
There should be a title 'Best results' in there 

![image](https://user-images.githubusercontent.com/24532683/122464988-c79f4200-cfb7-11eb-8d61-67fb1f891883.jpeg)

**Comment by symlinktech** [comment]
Please test after we send you the APK

**Comment by guille10k** [comment]
Ok

**Comment by guille10k** [comment]
Not loading because of the error on issue #8

**Comment by guille10k** [comment]
Perfect! Closing issue
