### ISSUE TITLE
Making teams allowed after deadline

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#91]
After the deadline has passed, there is still a chance to keep making teams if the app it's not refreshed. I guess with the site could happen too, but O didn't checked there. 

The solution is to check deadline when the user clicks Add team instead of directing him straightaway.

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/183403071-de96b5a3-fb64-45fa-b9bd-6d4cfe731876.png)

**Comment by symlinktech** [comment]
Please check. If let us know if there are any mistakes

**Comment by guille10k** [comment]
Works good. Only a small change on the message "Deadline is over".

Ideally, the message would be shown before making the team.

**Comment by symlinktech** [comment]
Please check. If let us know if there are any mistakes
