### ISSUE TITLE
Confirmation of losing team

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#93]
While making a team, if the user goes back, the team is lost. 

Solution: add an alert saying 'Are you sure you want to go back? Changes will be lost'

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/183354617-619863ff-9f9e-4ff9-b77f-41de18bb0b43.png)
Locally done. If any mistakes let us.

**Comment by guille10k** [comment]
Looks good.

Just add a change of line between "Are you sure you want to go back?" and "Changes will be lost."

Thanks

**Comment by symlinktech** [comment]
![image](https://user-images.githubusercontent.com/47890547/183405863-d0b1c1d7-3313-49fd-a4d3-ffd3e7576766.png)
Locally done. If any mistakes let us.

**Comment by guille10k** [comment]
Ok, I will let you know when I test it
