### ISSUE TITLE
Incomplete teams

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#96]
When there is an incomplete team we will colored that row in light red, and we will write "Incomplete team - review" where the points are now. Also, if it's still incomplete, we won't show points.

![E528A740-9F17-4057-9917-BFB24526F040](https://user-images.githubusercontent.com/24532683/188263112-c2002bb3-6177-418a-aba5-82d975ce9de6.JPG)

**Comment by symlinktech** [comment]
Done Locally. We will push next version
