### ISSUE TITLE
App settings: wrong picture

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomStatsApp#97]
Picture on settings is not the one displayed on the app

![image](https://user-images.githubusercontent.com/24532683/188270909-b0158ea9-67a8-496e-aa56-5303e5f7d2e3.png)

![image](https://user-images.githubusercontent.com/24532683/188270931-1e2c1cfe-f220-4fc5-beb0-4aaac9d3e146.png)

**Comment by symlinktech** [comment]
It's working fine. Please see this video.
https://www.loom.com/share/2c383f6ee50b4fff9907eaf48e6e445f
